services:
  app:
    build: .
    environment:
      - HOME_DIR
      - OUTPUT_DIR
      - DMS_INSTANCE_NAME
      - DMS_OUTPUT_DIR
      - DMS_GAME_SERVER_IP
      - DMS_PORT
      - DMS_DB_URL
      - DMS_DB_PORT
      - DMS_DB_USR
      - DMS_DB_PW
      - DMS_DB_SCHEMA
      - DMS_EXTERNAL_URL
      - DMS_DISCORD_ENABLED
      - DMS_DISCORD_TOKEN
      - DMS_DISCORD_CHANNEL_ID
      - DMS_IPB_ENABLED
      - DMS_IPB_API_URL
      - DMS_IPB_API_KEY
      - DMS_IPB_FORUM_ID
      - DMS_IPB_AUTHOR_ID
      - DMS_IPB_TOPIC_SUFFIX
      - DMS_IPB_POST_PREFIX
      - DMS_IPB_LINK_TEXT
    volumes:
      - ${DMS_OUTPUT_DIR}:${OUTPUT_DIR}
    ports:
      - ${DMS_PORT}:${DMS_PORT}/udp
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    ports:
      - ${DMS_DB_PORT}:${DMS_DB_PORT}
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DMS_DB_PW}
      - MYSQL_PASSWORD=${DMS_DB_PW}
      - MYSQL_USER=${DMS_DB_USR}
      - MYSQL_DATABASE=${DMS_DB_SCHEMA}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always