version: '3.9'

services:
  app:
    build: .
    environment:
      DMS_SV_IP:
      DMS_PORT:
      DMS_DB_URL: "${DMS_DB_URL:-db}"
      DMS_DB_PORT: "${DMS_DB_PORT:-3306}"
      DMS_DB_USR: "${DMS_DB_USR:-secret}"
      DMS_DB_PW: "${DMS_DB_PW:-secret}"
      DMS_DB_SCH: "${DMS_DB_SCH:-dods-match-stats}"
      DMS_HOME: "${DMS_HOME:-/opt/dods-match-stats}"
      DMS_HTML_OUTPUT: "${DMS_HTML_OUTPUT:-/var/www/dods-match-stats/html}"
    volumes:
      - ${DMS_HTML_OUTPUT}:${DMS_HTML_OUTPUT}
    ports:
      - ${DMS_PORT}:${DMS_PORT}/udp
    command: >
      /bin/bash -c 'cp ${DMS_HOME}/assets/paper.jpg ${DMS_HTML_OUTPUT}
      && ${DMS_HOME}/scripts/dods-match-stats.sh dms-instance-1'
    #networks:
    #  - database
    #links:
    #  - mysql
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    ports:
      - ${DMS_DB_PORT}:${DMS_DB_PORT}
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DMS_DB_PW}
      - MYSQL_PASSWORD=${DMS_DB_PW}
      - MYSQL_USER=${DMS_DB_USR}
      - MYSQL_DATABASE=${DMS_DB_SCH}
    #networks:
    #  - database
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always

#networks:
#  database:
#    external: true