version: '3.9'

services:
  app:
    build: .
    environment:
      - DMS_SV_IP
      - DMS_PORT
      - DMS_DB_URL
      - DMS_DB_PORT
      - DMS_DB_USR
      - DMS_DB_PW
      - DMS_DB_SCH
      - DMS_HOME
      - DMS_HTML_OUTPUT
    volumes:
      - ${DMS_HTML_OUTPUT}:${DMS_HTML_OUTPUT}
    ports:
      - ${DMS_PORT}:${DMS_PORT}/udp
    command:
      - cp ${DMS_HOME}/assets/paper.jpg ${DMS_HTML_OUTPUT}
      - /bin/bash ${DMS_HOME}/scripts/dods-match-stats.sh dms-instance-1
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    ports:
      - ${DMS_DB_PORT}:${DMS_DB_PORT}
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DMS_DB_PW}
      - MYSQL_PASSWORD=${DMS_DB_PW}
      - MYSQL_USER=${DMS_DB_USR}
      - MYSQL_DATABASE=${DMS_DB_SCH}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always